# Site configuration needed for jerkyll to know what to start the site link as lol
baseurl: ''

exclude:
  - .github/
  - .gitattributes
  - .gitignore
  - Utilities/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE